name: Deploy to Github Pages

on:
  push:
    branches:
      - feature-nextjs
 
jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '17.8.0'
          cache: 'npm'

      - name: Build
        run: |
          npm i --legacy-peer-deps
          npm run build
          npm run export
          touch out/.nojekyll
          touch out/CNAME
          echo \"topledger.xyz\" >> out/CNAME
          git add out/ 
          git commit -m \"Deploy to gh-pages\" 
          git subtree push --prefix out origin gh-pages"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
